package com.example.appfinal.staticElements

import androidx.compose.runtime.Composable
import androidx.lifecycle.viewmodel.compose.viewModel
import com.example.appfinal.R
import com.example.appfinal.viewModel.TarjetasViewModel

@Composable
fun LoadImages() {
    val imagesViewModel: TarjetasViewModel = viewModel()
    // cargar tarjetas de categoría "animales"
    imagesViewModel.saveImageReference(R.drawable.abeja.toString(), "animales", "abeja", R.drawable.abeja)
    imagesViewModel.saveImageReference(R.drawable.ballena.toString(), "animales", "ballena", R.drawable.ballena)
    imagesViewModel.saveImageReference(R.drawable.burro.toString(), "animales", "burro", R.drawable.burro)
    imagesViewModel.saveImageReference(R.drawable.cabra.toString(), "animales", "cabra", R.drawable.cabra)
    imagesViewModel.saveImageReference(R.drawable.cerdo.toString(), "animales", "cerdo", R.drawable.cerdo)
    imagesViewModel.saveImageReference(R.drawable.conejo.toString(), "animales", "conejo", R.drawable.conejo)
    imagesViewModel.saveImageReference(R.drawable.cucaracha.toString(), "animales", "cucaracha", R.drawable.cucaracha)
    imagesViewModel.saveImageReference(R.drawable.delfin.toString(), "animales", "delfín", R.drawable.delfin)
    imagesViewModel.saveImageReference(R.drawable.gallo.toString(), "animales", "gallo", R.drawable.gallo)
    imagesViewModel.saveImageReference(R.drawable.gato.toString(), "animales", "gato", R.drawable.gato)
    imagesViewModel.saveImageReference(R.drawable.iguana.toString(), "animales", "iguana", R.drawable.iguana)
    imagesViewModel.saveImageReference(R.drawable.insecto.toString(), "animales", "insecto", R.drawable.insecto)
    imagesViewModel.saveImageReference(R.drawable.loro.toString(), "animales", "loro", R.drawable.loro)
    imagesViewModel.saveImageReference(R.drawable.maripsa.toString(), "animales", "mariposa", R.drawable.maripsa)
    imagesViewModel.saveImageReference(R.drawable.oso.toString(), "animales", "oso", R.drawable.oso)
    imagesViewModel.saveImageReference(R.drawable.pajaro.toString(), "animales", "pájaro", R.drawable.pajaro)
    imagesViewModel.saveImageReference(R.drawable.panda.toString(), "animales", "panda", R.drawable.panda)
    imagesViewModel.saveImageReference(R.drawable.pato.toString(), "animales", "pato", R.drawable.pato)
    imagesViewModel.saveImageReference(R.drawable.pez.toString(), "animales", "pez", R.drawable.pez)
    imagesViewModel.saveImageReference(R.drawable.pulpo.toString(), "animales", "pulpo", R.drawable.pulpo)
    imagesViewModel.saveImageReference(R.drawable.tiburon.toString(), "animales", "tiburón", R.drawable.tiburon)
    imagesViewModel.saveImageReference(R.drawable.vaca.toString(), "animales", "vaca", R.drawable.vaca)
    // cargar tarjetas de categoría "colores"
    imagesViewModel.saveImageReference(R.drawable.amarillo.toString(), "colores", "amarillo", R.drawable.amarillo)
    imagesViewModel.saveImageReference(R.drawable.azul.toString(), "colores", "azul", R.drawable.azul)
    imagesViewModel.saveImageReference(R.drawable.beige.toString(), "colores", "beige", R.drawable.beige)
    imagesViewModel.saveImageReference(R.drawable.blanco.toString(), "colores", "blanco", R.drawable.blanco)
    imagesViewModel.saveImageReference(R.drawable.cafe.toString(), "colores", "café", R.drawable.cafe)
    imagesViewModel.saveImageReference(R.drawable.dorado.toString(), "colores", "dorado", R.drawable.dorado)
    imagesViewModel.saveImageReference(R.drawable.gris.toString(), "colores", "gris", R.drawable.gris)
    imagesViewModel.saveImageReference(R.drawable.morado.toString(), "colores", "morado", R.drawable.morado)
    imagesViewModel.saveImageReference(R.drawable.naranja.toString(), "colores", "naranja", R.drawable.naranja)
    imagesViewModel.saveImageReference(R.drawable.negro.toString(), "colores", "negro", R.drawable.negro)
    imagesViewModel.saveImageReference(R.drawable.plateado.toString(), "colores", "plateado", R.drawable.plateado)
    imagesViewModel.saveImageReference(R.drawable.rojo.toString(), "colores", "rojo", R.drawable.rojo)
    imagesViewModel.saveImageReference(R.drawable.rosa.toString(), "colores", "rosa", R.drawable.rosa)
    imagesViewModel.saveImageReference(R.drawable.verde.toString(), "colores", "verde", R.drawable.verde)
    // cargar tarjetas de categoría "cuerpo"
    imagesViewModel.saveImageReference(R.drawable.costado.toString(), "cuerpo", "costado", R.drawable.costado)
    imagesViewModel.saveImageReference(R.drawable.costado_2.toString(), "cuerpo", "costado", R.drawable.costado_2)
    imagesViewModel.saveImageReference(R.drawable.boca.toString(), "cuerpo", "boca", R.drawable.boca)
    imagesViewModel.saveImageReference(R.drawable.cabeza.toString(), "cuerpo", "cabeza", R.drawable.cabeza)
    imagesViewModel.saveImageReference(R.drawable.cabeza_2.toString(), "cuerpo", "cabeza", R.drawable.cabeza_2)
    imagesViewModel.saveImageReference(R.drawable.caderas.toString(), "cuerpo", "caderas", R.drawable.caderas)
    imagesViewModel.saveImageReference(R.drawable.caderas_2.toString(), "cuerpo", "caderas", R.drawable.caderas_2)
    imagesViewModel.saveImageReference(R.drawable.cuello.toString(), "cuerpo", "cuello", R.drawable.cuello)
    imagesViewModel.saveImageReference(R.drawable.cuello_2.toString(), "cuerpo", "cuello", R.drawable.cuello_2)
    imagesViewModel.saveImageReference(R.drawable.diente_caido.toString(), "cuerpo", "diente caído", R.drawable.diente_caido)
    imagesViewModel.saveImageReference(R.drawable.diente_caid_2.toString(), "cuerpo", "diente caído", R.drawable.diente_caid_2)
    imagesViewModel.saveImageReference(R.drawable.estomago.toString(), "cuerpo", "estómago", R.drawable.estomago)
    imagesViewModel.saveImageReference(R.drawable.hombro.toString(), "cuerpo", "hombro", R.drawable.hombro)
    imagesViewModel.saveImageReference(R.drawable.hombro_2.toString(), "cuerpo", "hombro", R.drawable.hombro_2)
    imagesViewModel.saveImageReference(R.drawable.musculo.toString(), "cuerpo", "músculo", R.drawable.musculo)
    imagesViewModel.saveImageReference(R.drawable.musculo_2.toString(), "cuerpo", "músculo", R.drawable.musculo_2)
    imagesViewModel.saveImageReference(R.drawable.nariz.toString(), "cuerpo", "nariz", R.drawable.nariz)
    imagesViewModel.saveImageReference(R.drawable.nariz_2.toString(), "cuerpo", "nariz", R.drawable.nariz_2)
    imagesViewModel.saveImageReference(R.drawable.piel.toString(), "cuerpo", "piel", R.drawable.piel)
    imagesViewModel.saveImageReference(R.drawable.piel_2.toString(), "cuerpo", "piel", R.drawable.piel_2)
    imagesViewModel.saveImageReference(R.drawable.pierna.toString(), "cuerpo", "pierna", R.drawable.pierna)
    imagesViewModel.saveImageReference(R.drawable.pierna_2.toString(), "cuerpo", "pierna", R.drawable.pierna_2)
    imagesViewModel.saveImageReference(R.drawable.rodilla.toString(), "cuerpo", "rodilla", R.drawable.rodilla)
    imagesViewModel.saveImageReference(R.drawable.rodilla_2.toString(), "cuerpo", "rodilla", R.drawable.rodilla_2)
    // cargar tarjetas de categoría "emociones"
    imagesViewModel.saveImageReference(R.drawable.acalorado.toString(), "emociones", "acalorado", R.drawable.acalorado)
    imagesViewModel.saveImageReference(R.drawable.acalorado_2.toString(), "emociones", "acalorado", R.drawable.acalorado_2)
    imagesViewModel.saveImageReference(R.drawable.avergonzado.toString(), "emociones", "avergonzado", R.drawable.avergonzado)
    imagesViewModel.saveImageReference(R.drawable.avergonzado_2.toString(), "emociones", "avergonzado", R.drawable.avergonzado_2)
    imagesViewModel.saveImageReference(R.drawable.decepcionado.toString(), "emociones", "decepcionado", R.drawable.decepcionado)
    imagesViewModel.saveImageReference(R.drawable.decepcionado_2.toString(), "emociones", "decepcionado", R.drawable.decepcionado_2)
    imagesViewModel.saveImageReference(R.drawable.deprimido.toString(), "emociones", "deprimido", R.drawable.deprimido)
    imagesViewModel.saveImageReference(R.drawable.deprimido_2.toString(), "emociones", "deprimido", R.drawable.deprimido_2)
    imagesViewModel.saveImageReference(R.drawable.emocionado.toString(), "emociones", "emocionado", R.drawable.emocionado)
    imagesViewModel.saveImageReference(R.drawable.feliz_3.toString(), "emociones", "feliz", R.drawable.feliz_3)
    imagesViewModel.saveImageReference(R.drawable.frustrado.toString(), "emociones", "frustrado", R.drawable.frustrado)
    imagesViewModel.saveImageReference(R.drawable.mareado.toString(), "emociones", "mareado", R.drawable.mareado)
    imagesViewModel.saveImageReference(R.drawable.nostalgico_2.toString(), "emociones", "nostálgico", R.drawable.nostalgico_2)
    // cargar tarjetas de categoría "profesiones"
    imagesViewModel.saveImageReference(R.drawable.amadecasa.toString(), "profesiones", "ama de casa", R.drawable.amadecasa)
    imagesViewModel.saveImageReference(R.drawable.astronauta.toString(), "profesiones", "astronauta", R.drawable.astronauta)
    imagesViewModel.saveImageReference(R.drawable.bancaria.toString(), "profesiones", "empleada bancaria", R.drawable.bancaria)
    imagesViewModel.saveImageReference(R.drawable.bombero.toString(), "profesiones", "bombero", R.drawable.bombero)
    imagesViewModel.saveImageReference(R.drawable.cajera.toString(), "profesiones", "cajera", R.drawable.cajera)
    imagesViewModel.saveImageReference(R.drawable.carpintero.toString(), "profesiones", "carpintero", R.drawable.carpintero)
    imagesViewModel.saveImageReference(R.drawable.chofer.toString(), "profesiones", "chofer", R.drawable.chofer)
    imagesViewModel.saveImageReference(R.drawable.cocinero.toString(), "profesiones", "cocinero", R.drawable.cocinero)
    imagesViewModel.saveImageReference(R.drawable.conserje.toString(), "profesiones", "conserje de zoológico", R.drawable.conserje)
    imagesViewModel.saveImageReference(R.drawable.conserje_2.toString(), "profesiones", "conserje", R.drawable.conserje_2)
    imagesViewModel.saveImageReference(R.drawable.dentista.toString(), "profesiones", "dentista", R.drawable.dentista)
    imagesViewModel.saveImageReference(R.drawable.doctor.toString(), "profesiones", "doctor", R.drawable.doctor)
    imagesViewModel.saveImageReference(R.drawable.ejercito_2.toString(), "profesiones", "ejército", R.drawable.ejercito_2)
    imagesViewModel.saveImageReference(R.drawable.jefe.toString(), "profesiones", "jefe", R.drawable.jefe)
    imagesViewModel.saveImageReference(R.drawable.maestro.toString(), "profesiones", "maestro", R.drawable.maestro)
    imagesViewModel.saveImageReference(R.drawable.mesero.toString(), "profesiones", "mesero", R.drawable.mesero)
    imagesViewModel.saveImageReference(R.drawable.ninera.toString(), "profesiones", "niñera", R.drawable.ninera)
    imagesViewModel.saveImageReference(R.drawable.obrero.toString(), "profesiones", "obrero", R.drawable.obrero)
    imagesViewModel.saveImageReference(R.drawable.payaso.toString(), "profesiones", "payaso", R.drawable.payaso)
    imagesViewModel.saveImageReference(R.drawable.peluquero.toString(), "profesiones", "peluquero", R.drawable.peluquero)
    imagesViewModel.saveImageReference(R.drawable.granjero.toString(), "profesiones", "granjero", R.drawable.granjero)
    imagesViewModel.saveImageReference(R.drawable.trabajador.toString(), "profesiones", "trabajador de construcción", R.drawable.trabajador)
    imagesViewModel.saveImageReference(R.drawable.vaquero.toString(), "profesiones", "vaquero", R.drawable.vaquero)
    // cargar tarjetas de categoría "vestimenta"
    imagesViewModel.saveImageReference(R.drawable.banano.toString(), "vestimenta", "banano", R.drawable.banano)
    imagesViewModel.saveImageReference(R.drawable.camisa.toString(), "vestimenta", "camisa", R.drawable.camisa)
    imagesViewModel.saveImageReference(R.drawable.canastoderopa.toString(), "vestimenta", "canasto de ropa", R.drawable.canastoderopa)
    imagesViewModel.saveImageReference(R.drawable.cascobombero.toString(), "vestimenta", "casco de bombero", R.drawable.cascobombero)
    imagesViewModel.saveImageReference(R.drawable.cordon.toString(), "vestimenta", "cordón", R.drawable.cordon)
    imagesViewModel.saveImageReference(R.drawable.gorrapolicia.toString(), "vestimenta", "gorra de policía", R.drawable.gorrapolicia)
    imagesViewModel.saveImageReference(R.drawable.guirnalda.toString(), "vestimenta", "guirnalda", R.drawable.guirnalda)
    imagesViewModel.saveImageReference(R.drawable.hombreras.toString(), "vestimenta", "hombreras", R.drawable.hombreras)
    imagesViewModel.saveImageReference(R.drawable.huarache.toString(), "vestimenta", "huarache", R.drawable.huarache)
    imagesViewModel.saveImageReference(R.drawable.jeans.toString(), "vestimenta", "jeans", R.drawable.jeans)
    imagesViewModel.saveImageReference(R.drawable.lazo.toString(), "vestimenta", "lazo", R.drawable.lazo)
    imagesViewModel.saveImageReference(R.drawable.mangacorta.toString(), "vestimenta", "manga corta", R.drawable.mangacorta)
    imagesViewModel.saveImageReference(R.drawable.mangalarga.toString(), "vestimenta", "manga larga", R.drawable.mangalarga)
    imagesViewModel.saveImageReference(R.drawable.placa.toString(), "vestimenta", "placa", R.drawable.placa)
    imagesViewModel.saveImageReference(R.drawable.ropainteriorlarga.toString(), "vestimenta", "ropa interior larga", R.drawable.ropainteriorlarga)
    imagesViewModel.saveImageReference(R.drawable.sombrerodecopa.toString(), "vestimenta", "sombrero de copa", R.drawable.sombrerodecopa)
    imagesViewModel.saveImageReference(R.drawable.sombrerovaquero.toString(), "vestimenta", "sombrero vaquero", R.drawable.sombrerovaquero)
    imagesViewModel.saveImageReference(R.drawable.trajebombero.toString(), "vestimenta", "traje de bombero", R.drawable.trajebombero)
    imagesViewModel.saveImageReference(R.drawable.trajenieve.toString(), "vestimenta", "traje de nieve", R.drawable.trajenieve)
    imagesViewModel.saveImageReference(R.drawable.uniformepolicia.toString(), "vestimenta", "uniforme de policía", R.drawable.uniformepolicia)
    imagesViewModel.saveImageReference(R.drawable.uniforme.toString(), "vestimenta", "uniforme", R.drawable.uniforme)
    imagesViewModel.saveImageReference(R.drawable.vestirse.toString(), "vestimenta", "vestirse", R.drawable.vestirse)
}

@Composable
fun LoadCategories() {
    val imagesViewModel: TarjetasViewModel = viewModel()
    imagesViewModel.nuevaCategoria("animales")
    imagesViewModel.nuevaCategoria("colores")
    imagesViewModel.nuevaCategoria("cuerpo")
    imagesViewModel.nuevaCategoria("emociones")
    imagesViewModel.nuevaCategoria("profesiones")
    imagesViewModel.nuevaCategoria("vestimenta")
}